import type { Business, Customer, Driver, Order } from './types';

export const MOCK_BUSINESSES: Business[] = [
  {
    id: 'b1',
    name: 'Farmacia Guadalajara Centro',
    category: 'Farmacia',
    address: 'Av. Hidalgo 12, Centro',
    hours: '8:00-22:00',
    isOpen: true,
    photo: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['recomendado', 'abierto'],
  },
  {
    id: 'b2',
    name: 'Farmacias del Ahorro',
    category: 'Farmacia',
    address: 'Calle 5 de Febrero 34',
    hours: '7:00-23:00',
    isOpen: true,
    photo: 'https://images.pexels.com/photos/3534905/pexels-photo-3534905.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['pedido_rapido', 'abierto'],
  },
  {
    id: 'b3',
    name: 'Supermercado Soriana',
    category: 'Supermercado',
    address: 'Blvd. Bernardo Quintana 100',
    hours: '7:00-22:00',
    isOpen: true,
    photo: 'https://images.pexels.com/photos/6168045/pexels-photo-6168045.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['abierto'],
  },
  {
    id: 'b4',
    name: 'La Europea Express',
    category: 'Supermercado',
    address: 'Av. Constituyentes 45',
    hours: '9:00-21:00',
    isOpen: false,
    photo: 'https://images.pexels.com/photos/6210805/pexels-photo-6210805.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: [],
  },
  {
    id: 'b5',
    name: 'Panadería La Esperanza',
    category: 'Panadería',
    address: 'Calle Allende 78',
    hours: '6:00-20:00',
    isOpen: true,
    photo: 'https://images.pexels.com/photos/5824883/pexels-photo-5824883.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['recomendado', 'abierto'],
  },
  {
    id: 'b6',
    name: 'Carnicería El Rastro',
    category: 'Carnicería',
    address: 'Merceteo La Cruz, Local 12',
    hours: '7:00-15:00',
    isOpen: true,
    photo: 'https://images.pexels.com/photos/8961342/pexels-photo-8961342.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['abierto'],
  },
  {
    id: 'b7',
    name: 'Ferretería El Tornillo',
    category: 'Ferretería',
    address: 'Av. Universidad 230',
    hours: '8:00-19:00',
    isOpen: true,
    photo: 'https://images.pexels.com/photos/209206/pexels-photo-209206.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['pedido_rapido', 'promocion', 'abierto'],
  },
  {
    id: 'b8',
    name: 'Papelería Crearte',
    category: 'Papelería',
    address: 'Calle Juárez 56',
    hours: '8:00-20:00',
    isOpen: true,
    photo: 'https://images.pexels.com/photos/1854652/pexels-photo-1854652.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['abierto'],
  },
  {
    id: 'b9',
    name: 'OXXO Centro',
    category: 'Tienda',
    address: 'Av. Hidalgo 200',
    hours: '24 horas',
    isOpen: true,
    photo: 'https://images.pexels.com/photos/2338407/pexels-photo-2338407.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['recomendado', 'pedido_rapido', 'abierto'],
  },
  {
    id: 'b10',
    name: 'Abarrotes Doña Mary',
    category: 'Abarrotes',
    address: 'Privada Las Palmas 4',
    hours: '7:00-22:00',
    isOpen: true,
    photo: 'https://images.pexels.com/photos/5475836/pexels-photo-5475836.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['promocion', 'abierto'],
  },
  {
    id: 'b11',
    name: 'Miscelánea La Esquina',
    category: 'Miscelánea',
    address: 'Calle Olmos 12',
    hours: '7:00-22:00',
    isOpen: false,
    photo: 'https://images.pexels.com/photos/4518962/pexels-photo-4518962.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: [],
  },
  {
    id: 'b12',
    name: 'Restaurante La Casona',
    category: 'Restaurante',
    address: 'Calle Constitución 5',
    hours: '12:00-22:00',
    isOpen: true,
    photo: 'https://images.pexels.com/photos/5997996/pexels-photo-5997996.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['recomendado', 'abierto'],
  },
  {
    id: 'b13',
    name: 'Tortillería La Milpa',
    category: 'Tienda',
    address: 'Calle Hidalgo 89',
    hours: '6:00-20:00',
    isOpen: true,
    photo: 'https://images.pexels.com/photos/5490248/pexels-photo-5490248.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['promocion', 'abierto'],
  },
  {
    id: 'b14',
    name: 'Verdulería El Huerto',
    category: 'Tienda',
    address: 'Mercado La Cruz',
    hours: '7:00-18:00',
    isOpen: true,
    photo: 'https://images.pexels.com/photos/264537/pexels-photo-264537.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['pedido_rapido', 'abierto'],
  },
  {
    id: 'b15',
    name: 'Distribuidora El Sol',
    category: 'Abarrotes',
    address: 'Av. Zaragoza 340',
    hours: '8:00-20:00',
    isOpen: true,
    photo: 'https://images.pexels.com/photos/6816869/pexels-photo-6816869.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['recomendado', 'abierto'],
  },
];

export const MOCK_DRIVERS: Driver[] = [
  { id: 'd1', name: 'Carlos Ramírez', phone: '442 111 2233', zone: 'Centro', status: 'disponible', rating: 4.9, totalDeliveries: 342 },
  { id: 'd2', name: 'Ana Martínez', phone: '442 222 3344', zone: 'Norte', status: 'en_ruta', rating: 4.8, totalDeliveries: 287 },
  { id: 'd3', name: 'Jorge Torres', phone: '442 333 4455', zone: 'Sur', status: 'disponible', rating: 4.7, totalDeliveries: 198 },
  { id: 'd4', name: 'María López', phone: '442 444 5566', zone: 'Juriquilla', status: 'disponible', rating: 5.0, totalDeliveries: 156 },
  { id: 'd5', name: 'Pedro Sánchez', phone: '442 555 6677', zone: 'El Pueblito', status: 'inactivo', rating: 4.6, totalDeliveries: 89 },
];

export const MOCK_CUSTOMERS: Customer[] = [
  { id: 'c1', name: 'Laura González', phone: '442 100 2000', address: 'Calle Independencia 15, Centro', totalOrders: 12 },
  { id: 'c2', name: 'Roberto Cruz', phone: '442 200 3000', address: 'Av. Constituyentes 230, Juriquilla', totalOrders: 5 },
  { id: 'c3', name: 'Patricia Ruiz', phone: '442 300 4000', address: 'Calle Olmos 45, El Pueblito', totalOrders: 8 },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'o1',
    code: 'BX-001',
    customerName: 'Laura González',
    customerPhone: '442 100 2000',
    address: 'Calle Independencia 15, Centro',
    reference: 'Portón negro',
    notes: 'Comprar 2L de leche y pan integral',
    serviceType: 'compras',
    establishments: ['OXXO Centro'],
    cost: 35,
    status: 'en_camino',
    driverId: 'd1',
    createdAt: Date.now() - 3600000,
    updatedAt: Date.now() - 1200000,
    timeline: [
      { status: 'solicitado', label: 'Pedido solicitado', timestamp: Date.now() - 3600000 },
      { status: 'confirmado', label: 'Pedido confirmado', timestamp: Date.now() - 3000000 },
      { status: 'en_compra', label: 'Repartidor en compra', timestamp: Date.now() - 1800000 },
      { status: 'en_camino', label: 'Repartidor en camino', timestamp: Date.now() - 1200000 },
    ],
  },
  {
    id: 'o2',
    code: 'BX-002',
    customerName: 'Roberto Cruz',
    customerPhone: '442 200 3000',
    address: 'Av. Constituyentes 230, Juriquilla',
    notes: 'Recoger sobre en notaría',
    serviceType: 'envios_recolecciones',
    establishments: ['Notaría 15'],
    cost: 40,
    status: 'confirmado',
    driverId: 'd2',
    createdAt: Date.now() - 1800000,
    updatedAt: Date.now() - 600000,
    timeline: [
      { status: 'solicitado', label: 'Pedido solicitado', timestamp: Date.now() - 1800000 },
      { status: 'confirmado', label: 'Pedido confirmado', timestamp: Date.now() - 600000 },
    ],
  },
  {
    id: 'o3',
    code: 'BX-003',
    customerName: 'Patricia Ruiz',
    customerPhone: '442 300 4000',
    address: 'Calle Olmos 45, El Pueblito',
    notes: 'Paracetamol 500mg x2 y suero oral x1',
    serviceType: 'farmacia',
    establishments: ['Farmacia Guadalajara Centro'],
    cost: 30,
    status: 'solicitado',
    driverId: null,
    createdAt: Date.now() - 300000,
    updatedAt: Date.now() - 300000,
    timeline: [
      { status: 'solicitado', label: 'Pedido solicitado', timestamp: Date.now() - 300000 },
    ],
  },
];
